version: "3.8"
services:

  user-service_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-api
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Password123
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodb-vol:/data/db
      - ./mongo-init/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  mongodb-vol:
